export interface TutorialStep {
    id: number;
    title: string;
    description: string;
    details?: string[]; // Detailed bullet points
    image?: string; // Optional screenshot/illustration
    highlightElement?: string; // CSS selector to highlight
    position?: 'center' | 'top' | 'bottom'; // Modal position
}

export const tutorialSteps: TutorialStep[] = [
    {
        id: 1,
        title: "Welcome to IPB Logbook Generator",
        description: "Automated tool to generate and submit your logbook to IPB Student Portal easily and quickly.",
        details: [
            "• Automatically generate logbook entries from Excel files",
            "• Submit directly to IPB Student Portal",
            "• Edit and review before submission",
            "• Download results in various formats (CSV, XLSX, PDF)",
            "• Your data is safe - all processing is done locally"
        ],
        image: '/tutorial/welcome.png',
        position: 'center'
    },
    {
        id: 2,
        title: "Step 1: Authentication",
        description: "Choose one of the authentication methods to access IPB Student Portal.",
        details: [
            "Aktivitas ID (Required):",
            "  • Paste the full URL from IPB Student Portal",
            "  • Example: https://studentportal.ipb.ac.id/.../Index/abc123",
            "  • System will automatically extract the Aktivitas ID",
            "",
            "Method 1 - Username & Password (Recommended):",
            "  • Enter your IPB Username",
            "  • Enter your IPB Password",
            "  • Click 'Login with Credentials' button",
            "  • System will automatically retrieve session cookies",
            "",
            "Method 2 - Manual Cookies (Advanced):",
            "  • Open IPB Student Portal in your browser",
            "  • Login first",
            "  • Copy .AspNetCore.Cookies",
            "  • Paste into the provided form",
            "  • Click 'Validate Cookies'",
            "",
            "Resume Session:",
            "  • If you have a previous session, you can resume it",
            "  • Click 'Resume Session' button to continue",
            "",
            "Privacy Notice:",
            "  • Login data is NOT stored on the server",
            "  • All processing is done locally in your browser",
            "  • Cookies are only used to submit logbook"
        ],
        image: '/tutorial/step-1-auth.png',
        highlightElement: '#step-1',
        position: 'top'
    },
    {
        id: 3,
        title: "Step 2: Upload Excel File",
        description: "Upload your Excel file or ZIP package containing logbook entries.",
        details: [
            "Download Templates:",
            "  • Excel Template - Basic logbook format",
            "  • ZIP Package Example - Excel with supporting files",
            "",
            "Upload Options:",
            "  • Option 1: Excel Only (.xlsx, .xls, .csv)",
            "    - Upload Excel file",
            "    - Add supporting files manually in Step 3",
            "  • Option 2: ZIP Package (Recommended)",
            "    - Create folder with Excel + files/ subfolder",
            "    - Zip the folder and upload",
            "    - Supporting files will be automatically attached",
            "",
            "Required Excel Columns:",
            "  • Waktu - Date (DD/MM/YYYY format)",
            "  • Tstart - Start time (HH:MM format)",
            "  • Tend - End time (HH:MM format)",
            "  • JenisLogId - 1 (Pembimbingan), 2 (Ujian), or 3 (Kegiatan)",
            "  • IsLuring - 0 (Online), 1 (Offline), or 2 (Hybrid)",
            "  • Lokasi - Location text",
            "  • Keterangan - Activity description",
            "  • Dosen - Lecturer numbers (e.g., \"1\", \"2\", \"1,2\")",
            "  • FilePath - Path to supporting file (e.g., files/bukti1.pdf)",
            "",
            "Manual Entry Option:",
            "  • Click 'Skip Upload & Add Manually'",
            "  • Add entries one by one in Step 3",
            "",
            "Tips:",
            "  • Use ZIP package for automatic file attachment",
            "  • Ensure date and time formats are correct",
            "  • Maximum file size: 5MB"
        ],
        image: '/tutorial/step-2-upload.png',
        highlightElement: '#step-2',
        position: 'center'
    },
    {
        id: 4,
        title: "Step 3: Review & Submit",
        description: "Review all entries, edit if needed, and submit to IPB Student Portal.",
        details: [
            "Review Entries:",
            "  • View all entries in a table format",
            "  • Check dates, times, activities, and descriptions",
            "  • Pay attention to warnings if duplicates exist",
            "  • Use search and filters to find specific entries",
            "",
            "Search & Filter:",
            "  • Search by activity description",
            "  • Filter by date range",
            "  • Filter by activity type (Pembimbingan, Ujian, Kegiatan)",
            "  • Filter by mode (Online, Offline, Hybrid)",
            "",
            "Edit Entries:",
            "  • Click 'Edit' button on any entry",
            "  • Modify date, time, activity type, or description",
            "  • Upload or change supporting files",
            "  • Click 'Save' to save changes",
            "  • Click 'Cancel' to discard changes",
            "",
            "Add Manual Entry:",
            "  • Click 'Add Entry' button at the top",
            "  • Fill all required fields",
            "  • Upload supporting files if available",
            "  • Click 'Add Entry' to add to the list",
            "",
            "Delete Entry:",
            "  • Click 'Delete' button on any entry",
            "  • Confirm deletion in the modal",
            "  • Entry will be removed from the list",
            "",
            "Supporting Files:",
            "  • Upload files for each entry (optional)",
            "  • Supported formats: PDF, DOC, DOCX, JPG, PNG, ZIP",
            "  • Click 'View' to preview files",
            "  • Maximum 10MB per file",
            "",
            "Bulk File Upload:",
            "  • Upload multiple files at once",
            "  • Files will be listed for selection",
            "  • Attach files to entries individually",
            "",
            "Duplicate Warning:",
            "  • System detects entries with the same date",
            "  • Review duplicates before submitting",
            "  • You can still submit if intentional",
            "",
            "Submit:",
            "  • Click 'Submit to IPB Portal' when ready",
            "  • Wait for submission process",
            "  • View submission results (success/failed per entry)"
        ],
        image: '/tutorial/step-3-review.png',
        highlightElement: '#step-3',
        position: 'center'
    },
    {
        id: 5,
        title: "Additional Features",
        description: "Utilize additional features to maximize your app usage.",
        details: [
            "Download Logbook:",
            "  • Click 'Download' dropdown in submission results",
            "  • Choose format: CSV, XLSX, or PDF",
            "  • File automatically downloads to your computer",
            "",
            "View Submission Results:",
            "  • See detailed submission results after submitting",
            "  • Check which entries succeeded/failed",
            "  • View error messages for failed entries",
            "  • Download report in various formats",
            "",
            "Duplicate Warning Modal:",
            "  • Appears if duplicate entries are detected",
            "  • Shows list of entries with the same date",
            "  • Option to continue or review entries",
            "",
            "File Upload from ZIP:",
            "  • Upload ZIP package with Excel + files",
            "  • System automatically extracts and matches files",
            "  • Files are attached based on FilePath column",
            "",
            "Remove Uploaded Files:",
            "  • Remove entire uploaded file and its entries",
            "  • Click 'Remove' button on uploaded file card",
            "  • All entries from that file will be deleted",
            "",
            "Dark Mode:",
            "  • Toggle dark mode in the top-right corner",
            "  • Settings are saved automatically",
            "  • Works across all pages",
            "",
            "Tutorial:",
            "  • Access tutorial anytime via '?' button in top-right corner",
            "  • Tutorial will appear automatically for first-time users"
        ],
        image: '/tutorial/additional-features.png',
        position: 'center'
    },
    {
        id: 6,
        title: "Need Help?",
        description: "Don't hesitate to access this tutorial anytime!",
        details: [
            "How to Access Tutorial:",
            "  • Click the '?' (Help) button in the top-right corner",
            "  • Tutorial will reopen from the beginning",
            "",
            "Found a Bug or Error?",
            "  • Check browser console (F12) for error details",
            "  • Screenshot the error and report to developer",
            "  • Check if your Excel format is correct",
            "",
            "Common Issues:",
            "  • Invalid date format - Use DD/MM/YYYY",
            "  • Invalid time format - Use HH:MM (24-hour)",
            "  • Missing required columns in Excel",
            "  • File size too large - Maximum 5MB for upload",
            "  • Cookies expired - Re-authenticate in Step 1",
            "",
            "Tips & Best Practices:",
            "  • Always download and use the provided templates",
            "  • Review entries before submitting",
            "  • Backup your Excel files regularly",
            "  • Use ZIP package for entries with supporting files",
            "  • Ensure stable internet connection when submitting",
            "",
            "Enjoy using IPB Logbook Generator!",
            "  • Save time with automated uploads",
            "  • Submit logbook easily and quickly",
            "  • Focus on activities, not administration!"
        ],
        image: '/tutorial/help.png',
        position: 'center'
    }
];
